### ISSUE TITLE
Not working with 8.0.2

### ISSUE THREAD

**Issue by sclearion** [maniaplanet/netbeans-psr#7]
Followed all instructions on a vanilla install of net beans several times to no avail. Thanks anyway but gonna stick to using the tools from the Netbeans Inspector panel

**Comment by mTorres** [comment]
It's working here (Netbeans 8.0.2 also) though it's quite slow (maybe because my sources are on a network shared folder).

I'm triggering it manually: Source > Format (or Alt + Shift + T)

**Comment by sclearion** [comment]
I had to remove some artifact-ed NB config files from my project the restart NB. Its working now thanks
